name: Run US Economy News Scraper

on:
  schedule:
    - cron: '0 1 * * 1,3,5,0'  # 월,수,금,일 오전 1시(UTC)에 실행
    workflow_dispatch:  # 이 줄을 추가
    name: Run US Economy News Scraper


jobs:
  scrape-news:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests transformers googletrans==3.1.0a0 gspread oauth2client selenium webdriver_manager
    - name: Run scraper
      env:
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
      run: |
        echo "$GOOGLE_SHEETS_CREDENTIALS" > credentials.json
        python market_news.py

        
